version: '2'
services:
  web:
    image: lgabster/cv-app:0.1
    ports:
      - "80:3000"
    depends_on:
      - mongo
    networks:
      - nodemongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/cvapp"
  mongo:
    image: mongo:3
    command: mongod --smallfiles
    networks:
      - nodemongo
networks:
  nodemongo: